name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build armv7a Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set Up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build Project
        # Added -x lint to skip linting and speed up the "last try"
        run: ./gradlew clean assembleRelease -x lint

      - name: Run Local Tests
        run: ./gradlew test

      - name: Upload Unsigned armv7a APK
        uses: actions/upload-artifact@v7
        with:
          name: nextplayer-release-unsigned
          # Without splits, the filename is standard
          path: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: build-reports
          path: app/build/reports
